# Generated by Django 6.0.6 on 2026-06-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del equipo (Ej: México)', max_length=100)),
                ('short_name', models.CharField(help_text='Abreviatura de 3 letras (Ej: MEX)', max_length=3)),
                ('flag_url', models.URLField(blank=True, help_text='URL de la bandera del equipo', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Fecha y hora de inicio del partido')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programado'), ('LIVE', 'En Vivo'), ('FINISHED', 'Finalizado')], default='SCHEDULED', max_length=20)),
                ('team_a_score', models.IntegerField(blank=True, help_text='Marcador del equipo A', null=True)),
                ('team_b_score', models.IntegerField(blank=True, help_text='Marcador del equipo B', null=True)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Costo en saldo virtual para predecir', max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, help_text='Bolsa acumulada virtual', max_digits=10)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_a', to='matches.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team_b', to='matches.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['date'],
            },
        ),
    ]
