# Generated by Django 6.0.6 on 2026-06-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.CharField(blank=True, help_text='Grupo o ronda (A, B, ..., R32, QF, SF, FINAL)', max_length=20),
        ),
    ]
