# Generated by Django 6.0.6 on 2026-06-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Costo en saldo virtual para predecir', max_digits=10),
        ),
    ]
